version: '3.8'

services:
  web:
    build: .
    ports:
      - "8900:8900"  # Daphne
      - "8400:8400"  # Uvicorn
    volumes:
      - .:/app
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - DJANGO_SETTINGS_MODULE=async_mysql_project.settings
    command: >
      sh -c "python entrypoint.py && daphne -b 0.0.0.0 -p 8900 async_mysql_project.asgi:application &&
            uvicorn async_mysql_project.asgi:application --host 0.0.0.0 --port 8400 &&
            python app_files.py"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1g

  worker:
    build: .
    volumes:
      - .:/app
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - DJANGO_SETTINGS_MODULE=async_mysql_project.settings
    command: >
      celery -A async_mysql_project.celery worker --loglevel=INFO --pool=solo
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1g

  flower:
    build: .
    ports:
      - "5252:5252"
    volumes:
      - .:/app
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - DJANGO_SETTINGS_MODULE=async_mysql_project.settings
    command: >
      celery -A async_mysql_project.celery flower --port=5252
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1g