# Generated by Django 5.1.2 on 2024-10-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datatable',
            options={'verbose_name': 'Data Table', 'verbose_name_plural': 'Data Tables'},
        ),
        migrations.RemoveField(
            model_name='datatable',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='datatable',
            name='description',
        ),
        migrations.AddField(
            model_name='datatable',
            name='address',
            field=models.CharField(default='Unknown Address', max_length=500, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='datatable',
            name='address_p',
            field=models.CharField(default='Unknown Address', max_length=500, verbose_name='address_p'),
        ),
        migrations.AddField(
            model_name='datatable',
            name='benefit',
            field=models.CharField(default='Unknown Address', max_length=500, verbose_name='benefit'),
        ),
        migrations.AddField(
            model_name='datatable',
            name='certificate',
            field=models.CharField(default='Unknown Address', max_length=500, verbose_name='certificate'),
        ),
        migrations.AddField(
            model_name='datatable',
            name='certificate_no',
            field=models.CharField(default='Unknown Address', max_length=500, verbose_name='certificate_no'),
        ),
        migrations.AddField(
            model_name='datatable',
            name='color',
            field=models.CharField(blank=True, default='Unknown Address', max_length=500, null=True, verbose_name='color'),
        ),
        migrations.AddField(
            model_name='datatable',
            name='comment',
            field=models.CharField(default='Unknown Address', max_length=500, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='datatable',
            name='cost',
            field=models.CharField(default='Unknown Address', max_length=500, verbose_name='cost'),
        ),
        migrations.AddField(
            model_name='datatable',
            name='date_number_cancellation',
            field=models.CharField(default='Unknown Address', max_length=500, verbose_name='date_number_cancellation'),
        ),
        migrations.AddField(
            model_name='datatable',
            name='date_number_get',
            field=models.CharField(default='Unknown Address', max_length=500, verbose_name='date_number_get'),
        ),
        migrations.AddField(
            model_name='datatable',
            name='date_number_no_one',
            field=models.CharField(default='Unknown Address', max_length=500, verbose_name='date_number_no_one'),
        ),
        migrations.AddField(
            model_name='datatable',
            name='date_number_no_two',
            field=models.CharField(default='Unknown Address', max_length=500, verbose_name='date_number_no_two'),
        ),
        migrations.AddField(
            model_name='datatable',
            name='date_post',
            field=models.CharField(default='Unknown Address', max_length=500, verbose_name='date_post'),
        ),
        migrations.AddField(
            model_name='datatable',
            name='id_id',
            field=models.CharField(default='Unknown Address', max_length=500, verbose_name='id_id'),
        ),
        migrations.AddField(
            model_name='datatable',
            name='location',
            field=models.CharField(default='Unknown Address', max_length=500, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='datatable',
            name='number',
            field=models.CharField(default='Unknown Address', max_length=500, verbose_name='number'),
        ),
        migrations.AddField(
            model_name='datatable',
            name='reason',
            field=models.CharField(default='Unknown Address', max_length=500, verbose_name='reason'),
        ),
        migrations.AddField(
            model_name='datatable',
            name='snils',
            field=models.CharField(default='Unknown Address', max_length=500, verbose_name='snils'),
        ),
        migrations.AddField(
            model_name='datatable',
            name='track',
            field=models.CharField(default='Unknown Address', max_length=500, verbose_name='track'),
        ),
        migrations.AddField(
            model_name='datatable',
            name='year',
            field=models.CharField(default='Unknown Address', max_length=500, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='name',
            field=models.CharField(default='Unknown Address', max_length=500, verbose_name='name'),
        ),
        migrations.AlterModelTable(
            name='datatable',
            table='services',
        ),
    ]
