# Generated by Django 5.1.2 on 2025-08-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='paid_last_year',
            field=models.TextField(default='', verbose_name='Paid Last Year'),
        ),
        migrations.AddField(
            model_name='services',
            name='remainder_old_year',
            field=models.TextField(default='', verbose_name='Remainder Old Year'),
        ),
        migrations.AddField(
            model_name='services_backup_one',
            name='paid_last_year',
            field=models.TextField(default='', verbose_name='Paid Last Year'),
        ),
        migrations.AddField(
            model_name='services_backup_one',
            name='remainder_old_year',
            field=models.TextField(default='', verbose_name='Remainder Old Year'),
        ),
        migrations.AddField(
            model_name='services_backup_two',
            name='paid_last_year',
            field=models.TextField(default='', verbose_name='Paid Last Year'),
        ),
        migrations.AddField(
            model_name='services_backup_two',
            name='remainder_old_year',
            field=models.TextField(default='', verbose_name='Remainder Old Year'),
        ),
        migrations.AlterField(
            model_name='services',
            name='DopFC',
            field=models.TextField(default='', verbose_name='DopFC'),
        ),
        migrations.AlterField(
            model_name='services',
            name='KOSGU',
            field=models.TextField(default='', verbose_name='KOSGU'),
        ),
        migrations.AlterField(
            model_name='services',
            name='KTSSR',
            field=models.TextField(default='', verbose_name='KTSSR'),
        ),
        migrations.AlterField(
            model_name='services',
            name='NMCC',
            field=models.TextField(default='', verbose_name='NMCC'),
        ),
        migrations.AlterField(
            model_name='services',
            name='april',
            field=models.TextField(default='', verbose_name='April'),
        ),
        migrations.AlterField(
            model_name='services',
            name='august',
            field=models.TextField(default='', verbose_name='August'),
        ),
        migrations.AlterField(
            model_name='services',
            name='color',
            field=models.TextField(default='', verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='services',
            name='contract_balance',
            field=models.TextField(default='', verbose_name='Contract Balance'),
        ),
        migrations.AlterField(
            model_name='services',
            name='contract_date',
            field=models.TextField(default='', verbose_name='Contract Date'),
        ),
        migrations.AlterField(
            model_name='services',
            name='contract_number',
            field=models.TextField(default='', verbose_name='Contract Number'),
        ),
        migrations.AlterField(
            model_name='services',
            name='contract_price',
            field=models.TextField(default='', verbose_name='Contract Price'),
        ),
        migrations.AlterField(
            model_name='services',
            name='counterparty',
            field=models.TextField(default='', verbose_name='Counterparty'),
        ),
        migrations.AlterField(
            model_name='services',
            name='date_april',
            field=models.TextField(default='', verbose_name='Date April'),
        ),
        migrations.AlterField(
            model_name='services',
            name='date_august',
            field=models.TextField(default='', verbose_name='Date August'),
        ),
        migrations.AlterField(
            model_name='services',
            name='date_december',
            field=models.TextField(default='', verbose_name='Date December'),
        ),
        migrations.AlterField(
            model_name='services',
            name='date_february',
            field=models.TextField(default='', verbose_name='Date February'),
        ),
        migrations.AlterField(
            model_name='services',
            name='date_january_one',
            field=models.TextField(default='', verbose_name='Date January One'),
        ),
        migrations.AlterField(
            model_name='services',
            name='date_january_two',
            field=models.TextField(default='', verbose_name='Date January Two'),
        ),
        migrations.AlterField(
            model_name='services',
            name='date_july',
            field=models.TextField(default='', verbose_name='Date July'),
        ),
        migrations.AlterField(
            model_name='services',
            name='date_june',
            field=models.TextField(default='', verbose_name='Date June'),
        ),
        migrations.AlterField(
            model_name='services',
            name='date_march',
            field=models.TextField(default='', verbose_name='Date March'),
        ),
        migrations.AlterField(
            model_name='services',
            name='date_may',
            field=models.TextField(default='', verbose_name='Date May'),
        ),
        migrations.AlterField(
            model_name='services',
            name='date_november',
            field=models.TextField(default='', verbose_name='Date November'),
        ),
        migrations.AlterField(
            model_name='services',
            name='date_october',
            field=models.TextField(default='', verbose_name='Date October'),
        ),
        migrations.AlterField(
            model_name='services',
            name='date_september',
            field=models.TextField(default='', verbose_name='Date September'),
        ),
        migrations.AlterField(
            model_name='services',
            name='december',
            field=models.TextField(default='', verbose_name='December'),
        ),
        migrations.AlterField(
            model_name='services',
            name='end_date',
            field=models.TextField(default='', verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='services',
            name='execution',
            field=models.TextField(default='', verbose_name='Execution'),
        ),
        migrations.AlterField(
            model_name='services',
            name='execution_contract_fact',
            field=models.TextField(default='', verbose_name='Execution Contract Fact'),
        ),
        migrations.AlterField(
            model_name='services',
            name='execution_contract_plan',
            field=models.TextField(default='', verbose_name='Execution Contract Plan'),
        ),
        migrations.AlterField(
            model_name='services',
            name='february',
            field=models.TextField(default='', verbose_name='February'),
        ),
        migrations.AlterField(
            model_name='services',
            name='id_id',
            field=models.TextField(default='', verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='services',
            name='initiator',
            field=models.TextField(default='', verbose_name='Initiator'),
        ),
        migrations.AlterField(
            model_name='services',
            name='january_one',
            field=models.TextField(default='', verbose_name='January One'),
        ),
        migrations.AlterField(
            model_name='services',
            name='january_two',
            field=models.TextField(default='', verbose_name='January Two'),
        ),
        migrations.AlterField(
            model_name='services',
            name='july',
            field=models.TextField(default='', verbose_name='July'),
        ),
        migrations.AlterField(
            model_name='services',
            name='june',
            field=models.TextField(default='', verbose_name='June'),
        ),
        migrations.AlterField(
            model_name='services',
            name='march',
            field=models.TextField(default='', verbose_name='March'),
        ),
        migrations.AlterField(
            model_name='services',
            name='may',
            field=models.TextField(default='', verbose_name='May'),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.TextField(default='', verbose_name='Service Name'),
        ),
        migrations.AlterField(
            model_name='services',
            name='november',
            field=models.TextField(default='', verbose_name='November'),
        ),
        migrations.AlterField(
            model_name='services',
            name='october',
            field=models.TextField(default='', verbose_name='October'),
        ),
        migrations.AlterField(
            model_name='services',
            name='registration_number',
            field=models.TextField(default='', verbose_name='Registration Number'),
        ),
        migrations.AlterField(
            model_name='services',
            name='saving',
            field=models.TextField(default='', verbose_name='Saving'),
        ),
        migrations.AlterField(
            model_name='services',
            name='september',
            field=models.TextField(default='', verbose_name='September'),
        ),
        migrations.AlterField(
            model_name='services',
            name='status',
            field=models.TextField(default='', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='services',
            name='sum_april',
            field=models.TextField(default='', verbose_name='Sum April'),
        ),
        migrations.AlterField(
            model_name='services',
            name='sum_august',
            field=models.TextField(default='', verbose_name='Sum August'),
        ),
        migrations.AlterField(
            model_name='services',
            name='sum_december',
            field=models.TextField(default='', verbose_name='Sum December'),
        ),
        migrations.AlterField(
            model_name='services',
            name='sum_february',
            field=models.TextField(default='', verbose_name='Sum February'),
        ),
        migrations.AlterField(
            model_name='services',
            name='sum_january_one',
            field=models.TextField(default='', verbose_name='Sum January One'),
        ),
        migrations.AlterField(
            model_name='services',
            name='sum_january_two',
            field=models.TextField(default='', verbose_name='Sum January Two'),
        ),
        migrations.AlterField(
            model_name='services',
            name='sum_july',
            field=models.TextField(default='', verbose_name='Sum July'),
        ),
        migrations.AlterField(
            model_name='services',
            name='sum_june',
            field=models.TextField(default='', verbose_name='Sum June'),
        ),
        migrations.AlterField(
            model_name='services',
            name='sum_march',
            field=models.TextField(default='', verbose_name='Sum March'),
        ),
        migrations.AlterField(
            model_name='services',
            name='sum_may',
            field=models.TextField(default='', verbose_name='Sum May'),
        ),
        migrations.AlterField(
            model_name='services',
            name='sum_november',
            field=models.TextField(default='', verbose_name='Sum November'),
        ),
        migrations.AlterField(
            model_name='services',
            name='sum_october',
            field=models.TextField(default='', verbose_name='Sum October'),
        ),
        migrations.AlterField(
            model_name='services',
            name='sum_september',
            field=models.TextField(default='', verbose_name='Sum September'),
        ),
        migrations.AlterField(
            model_name='services',
            name='way',
            field=models.TextField(default='', verbose_name='Way'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='DopFC',
            field=models.TextField(default='', verbose_name='DopFC'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='KOSGU',
            field=models.TextField(default='', verbose_name='KOSGU'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='KTSSR',
            field=models.TextField(default='', verbose_name='KTSSR'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='NMCC',
            field=models.TextField(default='', verbose_name='NMCC'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='april',
            field=models.TextField(default='', verbose_name='April'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='august',
            field=models.TextField(default='', verbose_name='August'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='color',
            field=models.TextField(default='', verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='contract_balance',
            field=models.TextField(default='', verbose_name='Contract Balance'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='contract_date',
            field=models.TextField(default='', verbose_name='Contract Date'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='contract_number',
            field=models.TextField(default='', verbose_name='Contract Number'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='contract_price',
            field=models.TextField(default='', verbose_name='Contract Price'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='counterparty',
            field=models.TextField(default='', verbose_name='Counterparty'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='date_april',
            field=models.TextField(default='', verbose_name='Date April'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='date_august',
            field=models.TextField(default='', verbose_name='Date August'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='date_december',
            field=models.TextField(default='', verbose_name='Date December'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='date_february',
            field=models.TextField(default='', verbose_name='Date February'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='date_january_one',
            field=models.TextField(default='', verbose_name='Date January One'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='date_january_two',
            field=models.TextField(default='', verbose_name='Date January Two'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='date_july',
            field=models.TextField(default='', verbose_name='Date July'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='date_june',
            field=models.TextField(default='', verbose_name='Date June'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='date_march',
            field=models.TextField(default='', verbose_name='Date March'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='date_may',
            field=models.TextField(default='', verbose_name='Date May'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='date_november',
            field=models.TextField(default='', verbose_name='Date November'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='date_october',
            field=models.TextField(default='', verbose_name='Date October'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='date_september',
            field=models.TextField(default='', verbose_name='Date September'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='december',
            field=models.TextField(default='', verbose_name='December'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='end_date',
            field=models.TextField(default='', verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='execution',
            field=models.TextField(default='', verbose_name='Execution'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='execution_contract_fact',
            field=models.TextField(default='', verbose_name='Execution Contract Fact'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='execution_contract_plan',
            field=models.TextField(default='', verbose_name='Execution Contract Plan'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='february',
            field=models.TextField(default='', verbose_name='February'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='id_id',
            field=models.TextField(default='', verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='initiator',
            field=models.TextField(default='', verbose_name='Initiator'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='january_one',
            field=models.TextField(default='', verbose_name='January One'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='january_two',
            field=models.TextField(default='', verbose_name='January Two'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='july',
            field=models.TextField(default='', verbose_name='July'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='june',
            field=models.TextField(default='', verbose_name='June'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='march',
            field=models.TextField(default='', verbose_name='March'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='may',
            field=models.TextField(default='', verbose_name='May'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='name',
            field=models.TextField(default='', verbose_name='Service Name'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='november',
            field=models.TextField(default='', verbose_name='November'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='october',
            field=models.TextField(default='', verbose_name='October'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='registration_number',
            field=models.TextField(default='', verbose_name='Registration Number'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='saving',
            field=models.TextField(default='', verbose_name='Saving'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='september',
            field=models.TextField(default='', verbose_name='September'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='status',
            field=models.TextField(default='', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='sum_april',
            field=models.TextField(default='', verbose_name='Sum April'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='sum_august',
            field=models.TextField(default='', verbose_name='Sum August'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='sum_december',
            field=models.TextField(default='', verbose_name='Sum December'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='sum_february',
            field=models.TextField(default='', verbose_name='Sum February'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='sum_january_one',
            field=models.TextField(default='', verbose_name='Sum January One'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='sum_january_two',
            field=models.TextField(default='', verbose_name='Sum January Two'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='sum_july',
            field=models.TextField(default='', verbose_name='Sum July'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='sum_june',
            field=models.TextField(default='', verbose_name='Sum June'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='sum_march',
            field=models.TextField(default='', verbose_name='Sum March'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='sum_may',
            field=models.TextField(default='', verbose_name='Sum May'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='sum_november',
            field=models.TextField(default='', verbose_name='Sum November'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='sum_october',
            field=models.TextField(default='', verbose_name='Sum October'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='sum_september',
            field=models.TextField(default='', verbose_name='Sum September'),
        ),
        migrations.AlterField(
            model_name='services_backup_one',
            name='way',
            field=models.TextField(default='', verbose_name='Way'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='DopFC',
            field=models.TextField(default='', verbose_name='DopFC'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='KOSGU',
            field=models.TextField(default='', verbose_name='KOSGU'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='KTSSR',
            field=models.TextField(default='', verbose_name='KTSSR'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='NMCC',
            field=models.TextField(default='', verbose_name='NMCC'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='april',
            field=models.TextField(default='', verbose_name='April'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='august',
            field=models.TextField(default='', verbose_name='August'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='color',
            field=models.TextField(default='', verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='contract_balance',
            field=models.TextField(default='', verbose_name='Contract Balance'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='contract_date',
            field=models.TextField(default='', verbose_name='Contract Date'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='contract_number',
            field=models.TextField(default='', verbose_name='Contract Number'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='contract_price',
            field=models.TextField(default='', verbose_name='Contract Price'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='counterparty',
            field=models.TextField(default='', verbose_name='Counterparty'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='date_april',
            field=models.TextField(default='', verbose_name='Date April'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='date_august',
            field=models.TextField(default='', verbose_name='Date August'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='date_december',
            field=models.TextField(default='', verbose_name='Date December'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='date_february',
            field=models.TextField(default='', verbose_name='Date February'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='date_january_one',
            field=models.TextField(default='', verbose_name='Date January One'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='date_january_two',
            field=models.TextField(default='', verbose_name='Date January Two'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='date_july',
            field=models.TextField(default='', verbose_name='Date July'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='date_june',
            field=models.TextField(default='', verbose_name='Date June'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='date_march',
            field=models.TextField(default='', verbose_name='Date March'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='date_may',
            field=models.TextField(default='', verbose_name='Date May'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='date_november',
            field=models.TextField(default='', verbose_name='Date November'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='date_october',
            field=models.TextField(default='', verbose_name='Date October'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='date_september',
            field=models.TextField(default='', verbose_name='Date September'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='december',
            field=models.TextField(default='', verbose_name='December'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='end_date',
            field=models.TextField(default='', verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='execution',
            field=models.TextField(default='', verbose_name='Execution'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='execution_contract_fact',
            field=models.TextField(default='', verbose_name='Execution Contract Fact'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='execution_contract_plan',
            field=models.TextField(default='', verbose_name='Execution Contract Plan'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='february',
            field=models.TextField(default='', verbose_name='February'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='id_id',
            field=models.TextField(default='', verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='initiator',
            field=models.TextField(default='', verbose_name='Initiator'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='january_one',
            field=models.TextField(default='', verbose_name='January One'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='january_two',
            field=models.TextField(default='', verbose_name='January Two'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='july',
            field=models.TextField(default='', verbose_name='July'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='june',
            field=models.TextField(default='', verbose_name='June'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='march',
            field=models.TextField(default='', verbose_name='March'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='may',
            field=models.TextField(default='', verbose_name='May'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='name',
            field=models.TextField(default='', verbose_name='Service Name'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='november',
            field=models.TextField(default='', verbose_name='November'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='october',
            field=models.TextField(default='', verbose_name='October'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='registration_number',
            field=models.TextField(default='', verbose_name='Registration Number'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='saving',
            field=models.TextField(default='', verbose_name='Saving'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='september',
            field=models.TextField(default='', verbose_name='September'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='status',
            field=models.TextField(default='', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='sum_april',
            field=models.TextField(default='', verbose_name='Sum April'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='sum_august',
            field=models.TextField(default='', verbose_name='Sum August'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='sum_december',
            field=models.TextField(default='', verbose_name='Sum December'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='sum_february',
            field=models.TextField(default='', verbose_name='Sum February'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='sum_january_one',
            field=models.TextField(default='', verbose_name='Sum January One'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='sum_january_two',
            field=models.TextField(default='', verbose_name='Sum January Two'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='sum_july',
            field=models.TextField(default='', verbose_name='Sum July'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='sum_june',
            field=models.TextField(default='', verbose_name='Sum June'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='sum_march',
            field=models.TextField(default='', verbose_name='Sum March'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='sum_may',
            field=models.TextField(default='', verbose_name='Sum May'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='sum_november',
            field=models.TextField(default='', verbose_name='Sum November'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='sum_october',
            field=models.TextField(default='', verbose_name='Sum October'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='sum_september',
            field=models.TextField(default='', verbose_name='Sum September'),
        ),
        migrations.AlterField(
            model_name='services_backup_two',
            name='way',
            field=models.TextField(default='', verbose_name='Way'),
        ),
        migrations.AlterField(
            model_name='services_three',
            name='DopFC',
            field=models.TextField(default='', verbose_name='DopFC'),
        ),
        migrations.AlterField(
            model_name='services_three',
            name='KOSGU',
            field=models.TextField(default='', verbose_name='KOSGU'),
        ),
        migrations.AlterField(
            model_name='services_three',
            name='budget_concluded',
            field=models.TextField(default='', verbose_name='Budget Concluded'),
        ),
        migrations.AlterField(
            model_name='services_three',
            name='budget_planned',
            field=models.TextField(default='', verbose_name='Budget Planned'),
        ),
        migrations.AlterField(
            model_name='services_three',
            name='budget_planned_old',
            field=models.TextField(default='', verbose_name='Budget Planned Old'),
        ),
        migrations.AlterField(
            model_name='services_three',
            name='budget_remainder',
            field=models.TextField(default='', verbose_name='Budget Remainder'),
        ),
        migrations.AlterField(
            model_name='services_three',
            name='color',
            field=models.TextField(default='', verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='services_three',
            name='id_id',
            field=models.TextField(default='', verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='services_three',
            name='off_budget_concluded',
            field=models.TextField(default='', verbose_name='Off Budget Concluded'),
        ),
        migrations.AlterField(
            model_name='services_three',
            name='off_budget_planned',
            field=models.TextField(default='', verbose_name='Off Budget Planned'),
        ),
        migrations.AlterField(
            model_name='services_three',
            name='off_budget_planned_old',
            field=models.TextField(default='', verbose_name='Off Budget Planned Old'),
        ),
        migrations.AlterField(
            model_name='services_three',
            name='off_budget_remainder',
            field=models.TextField(default='', verbose_name='Off Budget Remainder'),
        ),
        migrations.AlterField(
            model_name='services_two',
            name='DopFC',
            field=models.TextField(default='', verbose_name='DopFC'),
        ),
        migrations.AlterField(
            model_name='services_two',
            name='KOSGU',
            field=models.TextField(default='', verbose_name='KOSGU'),
        ),
        migrations.AlterField(
            model_name='services_two',
            name='budget_bargaining',
            field=models.TextField(default='', verbose_name='Budget Bargaining'),
        ),
        migrations.AlterField(
            model_name='services_two',
            name='budget_completed',
            field=models.TextField(default='', verbose_name='Budget Completed'),
        ),
        migrations.AlterField(
            model_name='services_two',
            name='budget_concluded',
            field=models.TextField(default='', verbose_name='Budget Concluded'),
        ),
        migrations.AlterField(
            model_name='services_two',
            name='budget_execution',
            field=models.TextField(default='', verbose_name='Budget Execution'),
        ),
        migrations.AlterField(
            model_name='services_two',
            name='budget_limit',
            field=models.TextField(default='', verbose_name='Budget Limit'),
        ),
        migrations.AlterField(
            model_name='services_two',
            name='budget_planned',
            field=models.TextField(default='', verbose_name='Budget Planned'),
        ),
        migrations.AlterField(
            model_name='services_two',
            name='budget_plans',
            field=models.TextField(default='', verbose_name='Budget Plans'),
        ),
        migrations.AlterField(
            model_name='services_two',
            name='budget_remainder',
            field=models.TextField(default='', verbose_name='Budget Remainder'),
        ),
        migrations.AlterField(
            model_name='services_two',
            name='color',
            field=models.TextField(default='', verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='services_two',
            name='id_id',
            field=models.TextField(default='', verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='services_two',
            name='name',
            field=models.TextField(default='', verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='services_two',
            name='off_budget_bargaining',
            field=models.TextField(default='', verbose_name='Off Budget Bargaining'),
        ),
        migrations.AlterField(
            model_name='services_two',
            name='off_budget_completed',
            field=models.TextField(default='', verbose_name='Off Budget Completed'),
        ),
        migrations.AlterField(
            model_name='services_two',
            name='off_budget_concluded',
            field=models.TextField(default='', verbose_name='Off Budget Concluded'),
        ),
        migrations.AlterField(
            model_name='services_two',
            name='off_budget_execution',
            field=models.TextField(default='', verbose_name='Off Budget Execution'),
        ),
        migrations.AlterField(
            model_name='services_two',
            name='off_budget_limit',
            field=models.TextField(default='', verbose_name='Off Budget Limit'),
        ),
        migrations.AlterField(
            model_name='services_two',
            name='off_budget_planned',
            field=models.TextField(default='', verbose_name='Off Budget Planned'),
        ),
        migrations.AlterField(
            model_name='services_two',
            name='off_budget_plans',
            field=models.TextField(default='', verbose_name='Off Budget Plans'),
        ),
        migrations.AlterField(
            model_name='services_two',
            name='off_budget_remainder',
            field=models.TextField(default='', verbose_name='Off Budget Remainder'),
        ),
    ]
